//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aug13.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable13Augg
    {
        public int id { get; set; }
        public string imgURL { get; set; }
        public string ProductName { get; set; }
        public string ProductPrice { get; set; }
    }
}
